import org.gradle.util.GradleVersion
import org.jetbrains.kotlin.gradle.dsl.Coroutines
import org.jetbrains.kotlin.gradle.dsl.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
println("Gradle Version: ${GradleVersion.current().version}")
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath ("org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30")
    }
}

plugins {
  //kotlin("common") version "1.2.30"
    id("ch.netzwerg.release") version "1.2.3"
    maven
    `build-scan`
}

val jvm by extra {
    subprojects.filter {
        it.name.endsWith("-jvm")
    }
}

configure(jvm) {
    plugins { jacoco }
}

buildScan {
    setLicenseAgreementUrl("https://gradle.com/terms-of-service")
    setLicenseAgree("yes")
}

apply {
    plugin("kotlin-platform-common")
}

allprojects {
    group = "info.kinterest"
    plugins { maven }
}



apply {
    from("common.gradle.kts")
    from("jvm.gradle.kts")
}

repositories {
    jcenter()
    mavenLocal()
}


