/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath ("org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30")
    }
}

plugins {
  //kotlin("common") version "1.2.30"
    id("ch.netzwerg.release") version "1.2.3"
    maven
}

apply {
    plugin("kotlin-platform-common")
}

apply {"common.gradle.kts"}
//apply()

allprojects {
    group = "info.kinterest"
}

val common by extra {
    subprojects.filter {
        !it.name.endsWith("-jvm") && !it.name.endsWith("-js")
    }
}

configure(common) {
    apply {
        plugin("kotlin-platform-common")
    }

    dependencies {
        "compile"(kotlin("stdlib-common"))
        "testCompile"(kotlin("test-annotations-common"))
        "testCompile"(kotlin("test-common"))
        //testCompile
        //compile "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version"
        //testCompile "org.jetbrains.kotlin:kotlin-test-annotations-common:$kotlin_version"
        //testCompile "org.jetbrains.kotlin:kotlin-test-common:$kotlin_version"
    }

    repositories {
        jcenter()
    }
}

repositories {
    jcenter()
}

